bind 0.0.0.0
port 6379
protected-mode no
daemonize yes
supervised no
pidfile /run/redis/redis-server.pid
dir /tmp
dbfilename dump.rdb
save ""
appendonly no
logfile ""
user default on nopass ~* -@all +ping +info +client
